// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {Script} from "forge-std/Script.sol";
import {console2} from "forge-std/console2.sol";
import {HydropumpLauncher} from "../../contracts/HydropumpLauncher.sol";

/// @title RegisterQuoteTokens
/// @dev Registers every quote token in script/quotes/quote-tokens.json, regenerated by
///      `node script/quotes/build-quote-tokens.mjs` from the live Hydrex asset list. Run as the launcher owner.
///      Set REFRESH_ONLY=true to update start ticks of already-registered quotes instead.
contract RegisterQuoteTokens is Script {
    function run() public {
        uint256 ownerKey = vm.envUint("DEPLOYER_KEY");
        address launcherAddress = vm.envAddress("LAUNCHER_ADDRESS");
        bool refreshOnly = vm.envOr("REFRESH_ONLY", false);

        string memory json = vm.readFile("script/quotes/quote-tokens.json");
        address[] memory addresses = vm.parseJsonAddressArray(json, ".addresses");
        int256[] memory rawTicks = vm.parseJsonIntArray(json, ".startTicks");

        int24[] memory startTicks = new int24[](rawTicks.length);
        bool[] memory enabled = new bool[](addresses.length);
        for (uint256 i = 0; i < rawTicks.length; i++) {
            startTicks[i] = int24(rawTicks[i]);
            enabled[i] = true;
        }

        console2.log("Launcher:", launcherAddress);
        console2.log("Quote tokens:", addresses.length);
        console2.log("Generated at:", vm.parseJsonString(json, ".generatedAt"));

        vm.startBroadcast(ownerKey);
        if (refreshOnly) {
            HydropumpLauncher(launcherAddress).setStartTicks(addresses, startTicks);
        } else {
            HydropumpLauncher(launcherAddress).configureQuoteTokens(addresses, enabled, startTicks);
        }
        vm.stopBroadcast();

        console2.log(refreshOnly ? "Start ticks refreshed." : "Quote tokens registered.");
    }
}
