// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import {Script} from "forge-std/Script.sol";
import {console2} from "forge-std/console2.sol";
import {PairDirectory} from "../../contracts/helpers/PairDirectory.sol";

/// @title RegisterQuoteTokens
/// @dev Registers every quote token in script/quotes/quote-tokens.json, regenerated by
///      `node script/quotes/build-quote-tokens.mjs` from hydrex-lists plus the live Hydrex asset list.
///      Run as the directory owner.
///
///      The `retired` block is registered in the same call with enabled = false. configureQuoteTokens
///      upserts one address at a time, so a token dropped from the list stays live on-chain until it is
///      explicitly disabled — omitting it is not a delisting.
///
///      Set REFRESH_ONLY=true to update start ticks of already-enabled quotes instead. That path skips
///      retired entries: setStartTicks reverts on a disabled quote.
contract RegisterQuoteTokens is Script {
    function run() public {
        uint256 ownerKey = vm.envUint("DEPLOYER_KEY");
        address directoryAddress = vm.envAddress("PAIR_DIRECTORY_ADDRESS");
        bool refreshOnly = vm.envOr("REFRESH_ONLY", false);

        string memory json = vm.readFile("script/quotes/quote-tokens.json");
        uint256 observed = vm.parseJsonUint(json, ".priceObservedAt");
        require(observed != 0 && observed <= block.timestamp, "invalid price timestamp");
        require(block.timestamp - observed <= 1 days, "quote file expired: regenerate");
        uint64 observedAt = uint64(observed);

        address[] memory active = vm.parseJsonAddressArray(json, ".addresses");
        int256[] memory activeTicks = vm.parseJsonIntArray(json, ".startTicks");
        bool[] memory activeEnabled = vm.parseJsonBoolArray(json, ".enabled");
        address[] memory retired = vm.parseJsonAddressArray(json, ".retired.addresses");
        int256[] memory retiredTicks = vm.parseJsonIntArray(json, ".retired.startTicks");

        require(active.length == activeTicks.length && active.length == activeEnabled.length, "active length mismatch");
        require(retired.length == retiredTicks.length, "retired length mismatch");

        console2.log("PairDirectory:", directoryAddress);
        console2.log("Generated at:", vm.parseJsonString(json, ".generatedAt"));
        console2.log("Active quotes:", active.length);
        console2.log("Retiring:", retired.length);

        if (refreshOnly) {
            int24[] memory ticks = new int24[](active.length);
            for (uint256 i = 0; i < active.length; i++) {
                ticks[i] = int24(activeTicks[i]);
            }

            vm.startBroadcast(ownerKey);
            PairDirectory(directoryAddress).setStartTicksWithTimestamp(active, ticks, observedAt);
            vm.stopBroadcast();

            console2.log("Start ticks refreshed.");
            return;
        }

        uint256 total = active.length + retired.length;
        address[] memory addresses = new address[](total);
        bool[] memory enabled = new bool[](total);
        int24[] memory startTicks = new int24[](total);

        for (uint256 i = 0; i < active.length; i++) {
            addresses[i] = active[i];
            enabled[i] = activeEnabled[i];
            startTicks[i] = int24(activeTicks[i]);
        }
        for (uint256 i = 0; i < retired.length; i++) {
            uint256 at = active.length + i;
            addresses[at] = retired[i];
            enabled[at] = false;
            startTicks[at] = int24(retiredTicks[i]);
        }

        vm.startBroadcast(ownerKey);
        PairDirectory(directoryAddress).configureQuoteTokensWithTimestamp(addresses, enabled, startTicks, observedAt);
        vm.stopBroadcast();

        console2.log("Quote tokens registered.");
    }
}
